# Generated by Django 5.2.7 on 2025-11-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
                ('saveData', models.CharField()),
            ],
        ),
    ]
