# Generated by Django 5.2.7 on 2025-11-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_savefile_savedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='savefile',
            name='username',
            field=models.CharField(default='matt080313', max_length=100),
            preserve_default=False,
        ),
    ]
