# Generated by Django 5.2.7 on 2025-11-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_savefile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='saveData',
            field=models.CharField(),
        ),
    ]
